In [2]:
import pandas as pd 
import numpy as np 
import os

In [4]:
search_path = 'info/GBM_BEV.xlsx'
info_path = 'info/path_num_info.csv'

In [6]:
search_df = pd.read_excel(search_path)
info_df = pd.read_csv(info_path)
search_list = np.array(search_df['path_num']).astype(int)
search_list

array([1324170, 1080180, 1294477, 1361375, 1346047, 1262688, 1202425,
       1239365, 1184565, 1249280, 1239371, 1301490, 1222663, 1351797,
       1187548, 1173547, 1192633, 1207053, 1337706, 1174869, 1037242,
       1233320,  923422, 1096638, 1183594, 1040863, 1135419, 1087875,
       1095160, 1013828,  976561, 1213266, 1117301,  950582, 1107078,
        907993,  992828,  918528, 1095343, 1033344, 1687331, 1457415,
       1414990, 1414988, 1415390, 1144248, 1458776, 1131756, 1514577,
       1493372, 1491609, 1559953, 1320313, 1462067, 1650793, 1250718,
       1638429, 1678804, 1664700, 1378733, 1736170, 1729330, 1756136,
       1640837, 1723850, 1742756, 1735168])

In [7]:
filter_df = info_df[info_df['path_num'].isin(search_list)]
filter_df

,Unnamed: 0,path_num,OS(d),non_cryo_file,cryo_file,non_cryo_file_num,cryo_file_num
1,1,907993,2412.0,"['39763.svs', '39764.svs']",[],2,0
8,8,950582,1399.0,"['39774.svs', '39775.svs', '39776.svs', '39801...",[],5,0
19,19,1037242,766.0,['39806.svs'],['39804.svs'],1,1
28,28,1087875,183.0,"['39840.svs', '39841.svs']",[],2,0
30,30,1117301,983.0,[],"['39834.svs', '39835.svs']",0,2
41,41,1187548,1224.0,"['39843.svs', '39844.svs', '39845.svs', '40082...",[],4,0
45,45,1202425,254.0,"['39991.svs', '39992.svs', '39993.svs', '39994...",[],8,0
46,46,1213266,240.0,"['39988.svs', '39989.svs', '39990.svs', '40081...",[],4,0
49,49,1222663,499.0,"['40000.svs', '40001.svs']","['39922.svs', '39923.svs', '39999.svs', '40084...",2,4
61,61,1337706,243.0,"['40026.svs', '40027.svs', '40028.svs']",[],3,0
65,65,1351797,213.0,['40017.svs'],[],1,0
69,69,1361375,234.0,"['40008.svs', '40009.svs', '40010.svs']",[],3,0
75,75,1457415,298.0,['40064.svs'],['40063.svs'],1,1
76,76,1458776,326.0,['40062.svs'],['40061.svs'],1,1
77,77,1462067,251.0,['40060.svs'],['40059.svs'],1,1
83,83,1514577,498.0,['40045.svs'],['40046.svs'],1,1
86,86,1559953,300.0,"['39883.svs', '39884.svs', '39885.svs', '39886...",[],33,0